### PR TITLE
feat: add `--tmux` flag (deprecates sk-tmux, fixes #596)

### LINKED ISSUE #596: Deprecate sk-tmux in flavor of the `--tmux` flag

### PR DESCRIPTION
**Pull request by LoricAndre**
The e2e are pretty basic but they should let us check the most delicate edge cases together with the unit tests

### CODE REVIEW

**Comment by LoricAndre** [comment]
Locking the PR until the tests are there

**Comment by ibhagwan** [comment]
@LoricAndre, FYI https://github.com/ibhagwan/fzf-lua/commit/d9db3b684384bcfd1393914b76f89f0205f183a3 added tmux support, all that's needed is to add the `--tmux` flag, either to setup or via command line, for example:
```vim
:FzfLua files fzf_opts.--tmux=center,40%,40%  fzf_bin=sk
```
The result:
image

I did discover one issue with tmux integration regarding the customization of the bg color which doesn't cover the entrire tmux popup, for example:
```sh
sk --height=100% --tmux center,40%,40% --color="bg:#ffcb8b"
```
image


Doing so with fzf yields:
image

**Comment by LoricAndre** [comment]
TYSM for being so quick to react !
The BG thing is a bit weird, looks like the text is colored, not the window.
Given that I'm rewriting the entire UI right now, I think it will stay that way for now unfortunately, unless someone else opens an issue about it.

**Comment by ibhagwan** [comment]
> TYSM for being so quick to react ! The BG thing is a bit weird, looks like the text is colored, not the window. Given that I'm rewriting the entire UI right now, I think it will stay that way for now unfortunately, unless someone else opens an issue about it.

No biggie as this is easily avoidable by not theming the background, just FYI.

Good luck on the rewrite and ty for your hard work  🙏

**Pull request merged**
