### PR TITLE
feat: allow more flexibility for use as a library

### PR DESCRIPTION
**Pull request by LoricAndre**
- Readd `cmd_collector` to options
- Readd `selector` to options
- Make `RankCriteria` public at crate root

### CODE REVIEW

**Comment by LoricAndre** [comment]
I know where the selector issue is coming from, I should be able to fix it today. Just a dumb mistake on my part

**Comment by LoricAndre** [comment]
I need to add a few examples too, to showcase this and serve as basic non-regression checks

**Comment by LoricAndre** [comment]
@idanarye can you check the selector now ?

**Comment by idanarye** [comment]
@LoricAndre Can confirm that `selector` works now. Thanks!

**Comment by LoricAndre** [comment]
If I can bother you some more, @idanarye could you take a quick look at the examples to make sure they reproduce (very basically) your use case ?

**Comment by idanarye** [comment]
@LoricAndre The examples seem adequate.

**Comment by LoricAndre** [comment]
@idanarye it's merged, so you should be able to use it from now on ! Please tell us about any issue you might face in the future, projects like yours are a great way to showcase's and progressively improve skim library features.

**Comment by idanarye** [comment]
Thanks! I've made a release for my plugin that migrates back to Skim.

**Comment by idanarye** [comment]
And... I had to yank it because of a bug. But that's on me (I think I know what it is) and I'll fix it later.

**Pull request merged**
